### ISSUE TITLE
Order Layers By... X &Y have been inverted

### ISSUE THREAD

**Issue by everydayslang** [Ashung/Automate-Sketch#169] opened 2019-04-10 16:18 UTC
I see that `Arrange > Order Layers By...` was one of the updates you made. I am familiar with the desire mentioned in #166 and am extremely happy to have this improvement, but it seems in making this update the default order of both `Position X` & `Position Y` has switched. `Position Y` now puts the layer with the highest value (further down the page) at the top of the layer list. Same with `Position X`, the higher values (further to the right) are first in the layer list. 

This was way more efficient in the old sort order where the layer with the lowest x/y value was first. This allows you to easily mirror the 'top to bottom' & 'left to right' with just one command.

**Comment by richardsison** [comment] 2019-04-11 07:39
Ok not just me… I rely on the old behaviour to make cleaning up of artboards really easy.

Hope this gets fixed soon :)

**Comment by everydayslang** [comment] 2019-04-11 16:54
🙏🙏🙏 Thanks for addressing this so quickly. 

However one additional thing... for the X position you have it described in the menu as top and bottom. I think you'd want to describe it in terms of left to right and vice versa...

X Position (Top-Bottom) = X Position (Left-Right)
X Position (Bottom-Top) = X Position (Right-Left)

**Comment by eaugustine** [comment] 2019-04-11 17:36
I'm having this issue too. I have a group of artboards which I've placed in a row left to right on the page in the order I want. Their order in the layers list may not be in that sequence. So I use Arrange > Order Layers by > Position X to get them to be ordered in the layers list from top to bottom the way I have them laid out from left to right. I then use another plugin to name the artboards sequentially.

Now, however, it orders them bottom to top, which is weird, so that when I go to change their names with sequential numbers, the numbering is backwards. So I have to do the extra step of Arrange > Reverse Layer Order, which is annoying and not expected behavior. Please change this back to the way it was working before, which made sense.

**Comment by eaugustine** [comment] 2019-04-11 17:43
That's got to be the quickest update fix ever! (Yeah, i know I probably just didn't have the update, but I swear it came up for me in Sketch right after I made my comment above!) I think the way you have made the Top-Bottom/Bottom-Top selection makes perfect sense, since we're talking about their position in the vertical layers list.

**Comment by richardsison** [comment] 2019-04-11 23:41
This is hands down the best plugin. @Ashung you are doing amazing work on this thing honestly. 

You're one of the main reasons keeping me from moving to Figma. I rely on this plugin for so many micro-interactions (like ordering groups by Y-position) that moving to another tool would be really difficult. I'm just so used to the functionality this plugin provides.

Thanks a lot!

🎉

**Comment by Ashung** [comment] 2019-04-12 03:40
@everydayslang The default layer list order of Sketch is from bottom to top. Bottom-Top means the layer with least x/y will in the bottom of layer list.

**Closed** 2019-04-12 03:40 UTC

**Comment by everydayslang** [comment] 2019-04-12 14:19
@Ashung Okay, I see your rationale, just wasn't immediately clear to me at the moment.
