### ISSUE TITLE
Add "Shrink instance to fit content." to the menu

### ISSUE THREAD

**Issue by ehaft21** [Ashung/Automate-Sketch#226] opened 2019-11-20 15:20 UTC
Can you add "Shrink instance to fit content." to the menu?  It only exists for symbols with smart layout in the right panel, so it currently cannot be set to a hotkey.

**Comment by Ashung** [comment] 2019-11-21 01:53
Duplicate of #207

**Closed** 2019-11-22 12:54 UTC
