### ISSUE TITLE
what happened to move Symbol master to another page?

### ISSUE THREAD

**Issue by Raghav789** [Ashung/Automate-Sketch#185] opened 2019-06-27 10:49 UTC
yes, what happened to it can't find it in symbol menu 
<img width="861" alt="Screenshot 2019-06-27 at 4 21 05 PM" src="https://user-images.githubusercontent.com/29393153/60260612-98d5c000-98f7-11e9-873b-48e19d9d640e.png">

**Comment by Ashung** [comment] 2019-06-27 13:26
Duplicate of #179 

Just drag and drop you symbol master layer to the page title in layer list panel.

**Closed by Ashung** 2019-06-27 13:26 UTC
